name: Deploy to Firebase

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12

    - name: Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      run: |
        npm install
        npm run generate
        npm run deploy
